# GitHub Actions 工作流名称
name: Pan1.me Auto Check-in

# 工作流的触发条件
on:
  # 1. 定时触发：使用 cron 表达式，时间为 UTC。
  #    下面的 '30 0 * * *' 代表每天 UTC 时间 00:30 (北京时间 08:30) 执行。
  schedule:
    - cron: '30 0 * * *'

  # 2. 手动触发：允许你在 Actions 页面手动点击 "Run workflow" 按钮来运行。
  #    这就是你需要的手动触发功能。
  workflow_dispatch:

# 定义工作流中的任务
jobs:
  # 定义一个名为 "check-in-job" 的任务
  check-in-job:
    # 指定运行此任务的虚拟机环境
    runs-on: ubuntu-latest
    
    # 定义任务中的步骤
    steps:
      # 第 1 步：检出代码
      # 目的是让虚拟机可以访问到仓库中的 checkin.py 等文件
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第 2 步：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 第 3 步：安装脚本所需的依赖库
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 第 4 步：执行签到脚本
      # 这一步是核心，注意 env 和 run 的缩进级别是相同的
      - name: Run check-in script
        env:
          PAN_COOKIE: ${{ secrets.PAN_COOKIE }}
          # 建议将 DEBUG_MODE 也设置为 Secret，方便在网页上开关调试模式
          DEBUG_MODE: ${{ secrets.DEBUG_MODE }}
        run: python checkin.py
