# GitHub Actions 工作流名称
name: Pan1.me Auto Check-in

on:
  # 定时触发：每天的 UTC 时间 0点30分（北京时间 8点30分）执行
  schedule:
    - cron: '30 0 * * *'

  # 手动触发：允许你在 GitHub Actions 页面手动运行此工作流
  workflow_dispatch:

jobs:
  check-in-job:
    # 使用最新的 Ubuntu 虚拟机环境
    runs-on: ubuntu-latest
    
    steps:
      # 第一步：检出你的代码库
      # 使得虚拟机可以访问到你的 checkin.py 文件
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第二步：设置 Python 环境
      # 使用 Python 3.9 版本
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 第三步：安装依赖库
      # 我们的脚本需要 `requests` 库来发送网络请求
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 第四步：执行签到脚本
      # 关键步骤！这里通过 `env` 将 GitHub Secret 传递给脚本
      - name: Run check-in script
        env:
          # `PAN_COOKIE` 是我们要在 GitHub 上设置的 Secret 名称
          PAN_COOKIE: ${{ secrets.PAN_COOKIE }}
          # `DEBUG_MODE` 是调试开关
          DEBUG_MODE: ${{ secrets.DEBUG_MODE }}
        run: python checkin.py

```> **注意**：我将 `DEBUG_MODE` 的值也改为了从 Secrets 读取 (`${{ secrets.DEBUG_MODE }}`)，这样更加灵活。你可以在 Secrets 中设置 `DEBUG_MODE` 为 `true` 来开启调试。如果不需要调试，删除这个 Secret 或将其值设为 `false` 即可。

请按照以上步骤检查，问题应该就能解决。最常见的就是**第一条：文件路径或名称不对**。
